# Generated by Django 4.2.6 on 2024-01-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('username', models.TextField(blank=True, max_length=30)),
                ('avatar_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
