# Generated by Django 4.2.6 on 2023-11-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
    ]
